package errs

import "net/http"

// Error codes related to installment
var (
	ErrInstallmentPlanIdInvalid                     = NewNormalError(NormalSubcategoryInstallment, 0, http.StatusBadRequest, "installment plan id is invalid")
	ErrInstallmentPlanNotFound                      = NewNormalError(NormalSubcategoryInstallment, 1, http.StatusBadRequest, "installment plan not found")
	ErrInstallmentItemIdInvalid                     = NewNormalError(NormalSubcategoryInstallment, 2, http.StatusBadRequest, "installment item id is invalid")
	ErrInstallmentItemNotFound                      = NewNormalError(NormalSubcategoryInstallment, 3, http.StatusBadRequest, "installment item not found")
	ErrInstallmentProviderInvalid                   = NewNormalError(NormalSubcategoryInstallment, 4, http.StatusBadRequest, "installment provider is invalid")
	ErrInstallmentAccountingModeInvalid             = NewNormalError(NormalSubcategoryInstallment, 5, http.StatusBadRequest, "installment accounting mode is invalid")
	ErrInstallmentDueDateSourceInvalid              = NewNormalError(NormalSubcategoryInstallment, 6, http.StatusBadRequest, "installment due date source is invalid")
	ErrInstallmentStorageModeInvalid                = NewNormalError(NormalSubcategoryInstallment, 7, http.StatusBadRequest, "installment storage mode is invalid")
	ErrInstallmentItemsInvalid                      = NewNormalError(NormalSubcategoryInstallment, 8, http.StatusBadRequest, "installment items are invalid")
	ErrInstallmentItemAlreadyPaid                   = NewNormalError(NormalSubcategoryInstallment, 9, http.StatusBadRequest, "installment item is already paid")
	ErrInstallmentItemNotPaid                       = NewNormalError(NormalSubcategoryInstallment, 10, http.StatusBadRequest, "installment item is not paid")
	ErrInstallmentLiabilityAccountInvalid           = NewNormalError(NormalSubcategoryInstallment, 11, http.StatusBadRequest, "installment liability account is invalid")
	ErrInstallmentPaymentAccountInvalid             = NewNormalError(NormalSubcategoryInstallment, 12, http.StatusBadRequest, "installment payment account is invalid")
	ErrInstallmentCurrencyInvalid                   = NewNormalError(NormalSubcategoryInstallment, 13, http.StatusBadRequest, "installment currency is invalid")
	ErrInstallmentPurchaseTransactionInvalid        = NewNormalError(NormalSubcategoryInstallment, 14, http.StatusBadRequest, "installment purchase transaction is invalid")
	ErrInstallmentPurchaseTransactionRequired       = NewNormalError(NormalSubcategoryInstallment, 15, http.StatusBadRequest, "installment purchase transaction is required")
	ErrInstallmentPurchaseCategoryRequired          = NewNormalError(NormalSubcategoryInstallment, 16, http.StatusBadRequest, "installment purchase category is required")
	ErrInstallmentRepaymentCategoryRequired         = NewNormalError(NormalSubcategoryInstallment, 17, http.StatusBadRequest, "installment repayment category is required")
	ErrInstallmentFeeCategoryRequired               = NewNormalError(NormalSubcategoryInstallment, 18, http.StatusBadRequest, "installment fee category is required")
	ErrInstallmentTransferCategoryRequired          = NewNormalError(NormalSubcategoryInstallment, 19, http.StatusBadRequest, "installment transfer category is required")
	ErrInstallmentHasPaidItemsCannotModify          = NewNormalError(NormalSubcategoryInstallment, 20, http.StatusBadRequest, "installment with paid items cannot be modified")
	ErrInstallmentHasPaidItemsCannotDelete          = NewNormalError(NormalSubcategoryInstallment, 21, http.StatusBadRequest, "installment with paid items cannot be deleted")
	ErrInstallmentGeneratedPurchaseCannotBeMissing  = NewNormalError(NormalSubcategoryInstallment, 22, http.StatusBadRequest, "generated installment purchase transaction cannot be missing")
	ErrInstallmentOnlyPurchaseRecognizedCanGenerate = NewNormalError(NormalSubcategoryInstallment, 23, http.StatusBadRequest, "only purchase recognized installment can generate purchase transaction")
	ErrInstallmentDateInvalid                       = NewNormalError(NormalSubcategoryInstallment, 24, http.StatusBadRequest, "installment date is invalid")
	ErrInstallmentAmountMismatch                    = NewNormalError(NormalSubcategoryInstallment, 25, http.StatusBadRequest, "installment amount does not match")
	ErrInstallmentPeriodCountInvalid                = NewNormalError(NormalSubcategoryInstallment, 26, http.StatusBadRequest, "installment period count is invalid")
	ErrInstallmentDuplicateItemSequence             = NewNormalError(NormalSubcategoryInstallment, 27, http.StatusBadRequest, "installment item sequence is duplicated")
	ErrInstallmentPaymentAccountRequired            = NewNormalError(NormalSubcategoryInstallment, 28, http.StatusBadRequest, "installment payment account is required")
	ErrInstallmentAccountRuleNotFound               = NewNormalError(NormalSubcategoryInstallment, 29, http.StatusBadRequest, "installment account rule not found")
	ErrInstallmentAccountRuleInvalid                = NewNormalError(NormalSubcategoryInstallment, 30, http.StatusBadRequest, "installment account rule is invalid")
	ErrInstallmentAccountRuleDisabled               = NewNormalError(NormalSubcategoryInstallment, 31, http.StatusBadRequest, "installment account rule is disabled")
	ErrInstallmentTimezoneInvalid                   = NewNormalError(NormalSubcategoryInstallment, 32, http.StatusBadRequest, "installment timezone is invalid")
)
